# Shared helpers for locating dependency headers and checking versions.

include_guard(GLOBAL)

function(_aperture_find_header_dir OUT_VAR FILENAME)
  foreach(_dir IN LISTS ARGN)
    if(_dir AND EXISTS "${_dir}/${FILENAME}")
      set(${OUT_VAR} "${_dir}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${OUT_VAR} "" PARENT_SCOPE)
endfunction()

function(_aperture_include_dir_from_target TARGET FILENAME OUT_VAR)
  set(${OUT_VAR} "" PARENT_SCOPE)
  if(NOT TARGET ${TARGET})
    return()
  endif()
  get_target_property(_incs ${TARGET} INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT _incs)
    return()
  endif()
  foreach(_inc IN LISTS _incs)
    string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" _inc "${_inc}")
    if(_inc MATCHES "^\\$<")
      continue()
    endif()
    if(_inc AND EXISTS "${_inc}/${FILENAME}")
      set(${OUT_VAR} "${_inc}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
endfunction()

function(_aperture_is_sdk_path PATH OUT_VAR)
  set(${OUT_VAR} FALSE PARENT_SCOPE)
  if(NOT APERTURE_VULKAN_SDK_DIR OR NOT PATH)
    return()
  endif()
  file(TO_CMAKE_PATH "${PATH}" _path)
  file(TO_CMAKE_PATH "${APERTURE_VULKAN_SDK_DIR}" _sdk)
  string(FIND "${_path}" "${_sdk}" _idx)
  if(_idx EQUAL 0)
    set(${OUT_VAR} TRUE PARENT_SCOPE)
  endif()
endfunction()

# VERSION meets MIN (unknown VERSION is not acceptable).
function(_aperture_version_meets VERSION MIN OUT_VAR)
  if(NOT VERSION OR NOT MIN)
    set(${OUT_VAR} FALSE PARENT_SCOPE)
    return()
  endif()
  if(VERSION VERSION_LESS MIN)
    set(${OUT_VAR} FALSE PARENT_SCOPE)
  else()
    set(${OUT_VAR} TRUE PARENT_SCOPE)
  endif()
endfunction()

function(_aperture_parse_vulkan_header_version INCLUDE_DIR OUT_VAR)
  set(${OUT_VAR} "" PARENT_SCOPE)
  set(_header "${INCLUDE_DIR}/vulkan/vulkan_core.h")
  if(NOT EXISTS "${_header}")
    return()
  endif()

  file(STRINGS "${_header}" _patch_line REGEX "^#define VK_HEADER_VERSION ")
  if(NOT _patch_line)
    return()
  endif()
  string(REGEX MATCH "[0-9]+$" _patch "${_patch_line}")

  set(_major "")
  set(_minor "")
  file(STRINGS "${_header}" _complete_line REGEX "^#define VK_HEADER_VERSION_COMPLETE")
  if(_complete_line MATCHES "VK_MAKE_API_VERSION\\([0-9]+,[\t ]*([0-9]+),[\t ]*([0-9]+)")
    set(_major "${CMAKE_MATCH_1}")
    set(_minor "${CMAKE_MATCH_2}")
  elseif(_complete_line MATCHES "VK_MAKE_VERSION\\(([0-9]+),[\t ]*([0-9]+)")
    set(_major "${CMAKE_MATCH_1}")
    set(_minor "${CMAKE_MATCH_2}")
  elseif(EXISTS "${INCLUDE_DIR}/vulkan/vulkan.h")
    file(STRINGS "${INCLUDE_DIR}/vulkan/vulkan.h" _api14 REGEX "^#define VK_API_VERSION_1_4")
    if(_api14)
      set(_major "1")
      set(_minor "4")
    endif()
  endif()

  if(NOT _major)
    return()
  endif()
  set(${OUT_VAR} "${_major}.${_minor}.${_patch}" PARENT_SCOPE)
endfunction()
